name: Linter
on:
  pull_request:
    branches: [ main ]
jobs:
  linter:
    name: "Check on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Lint
      run: |
        npm install
        npm run lint